#!/bin/bash
#BSUB -n 1
#BSUB -R "span[hosts=1]"

mkdir -p /export/cluster-tmp/chenyehu
export TMPDIR=/export/cluster-tmp/chenyehu


SEED=$1
data_name=$2
N=$3
TA=$4

matlab -nodisplay -nodesktop --use-single-comp-thread -r "addpath('~/gpml-matlab-v3.6-2015-07-07'); N=${N}; SEED=${SEED}; data_name='${data_name}'; test_anchor=${TA}; simulation;"
