#!/bin/bash

mkdir -p results

MAXSEED=25
declare -a data_names=("2Dplane" "Friedman")
declare -a NS=(100 200 300 400 500 600 700 800)
declare -a TAs=(0 1)

if [ $1 = "run" ]
then
    for SEED in $(seq 1 1 $MAXSEED); do
        for data_name in ${data_names[@]}; do
            for N in ${NS[@]}; do
                for TA in ${TAs[@]}; do
                    bsub -G SEAS-Lab-Garnett -o /dev/null -J "${data_name}${N}_${TA}_${SEED}" "./onerun $SEED $data_name $N $TA"
                done
            done
        done
    done
elif [ $1 = "summary" ]
then
    python utilities/plot_results.py -s $MAXSEED
fi