#!/bin/bash

mkdir -p results

MAXSEED=25
declare -a data_names=("2Dplane" "Friedman")
declare -a NS=(25 50 100 200 400 800 1600)

if [ $1 = "run" ]
then
    for SEED in $(seq 1 1 $MAXSEED); do
        for data_name in ${data_names[@]}; do
            for N in ${NS[@]}; do
                bsub -G SEAS-Lab-Garnett -o /dev/null -J "${data_name}${N}_${SEED}" "./onerun $SEED $data_name $N"
            done
        done
    done
elif [ $1 = "summary" ]
then
    python utilities/plot_results.py -s $MAXSEED
fi