#!/bin/bash

mkdir -p results

MAXSEED=25
declare -a data_names=("twoDplane" "Friedman")
declare -a NS=(50 100 150 200 250 300)
declare -a NS=(1000)
declare -a TAs=(0)

if [ $1 = "run" ]
then
    for SEED in $(seq 1 1 $MAXSEED); do
        for data_name in ${data_names[@]}; do
            for N in ${NS[@]}; do
                for TA in ${TAs[@]}; do
                    bsub -G SEAS-Lab-Garnett -o /dev/null -J "${data_name}${N}_${TA}_${SEED}" "./onerun $SEED $data_name $N $TA"
                done
            done
        done
    done
elif [ $1 = "summary" ]
then
    python utilities/plot_results.py -s $MAXSEED -t 0 -e pop
    python utilities/plot_results.py -s $MAXSEED -t 0 -e ind
fi

# scp chenyehu@ssh8.engr.wustl.edu:budgeted-conjoint-analysis/results/*pdf ./results/