#!/bin/bash

mkdir -p results2

MAXSEED=25
declare -a data_names=("twoDplane" "Friedman")
N=1000
declare -a TOTAL_SIZES=(200)
declare -a policy_names=("UNIFORM" "BALD" "GRADBALD" "US" "GRADUS")

if [ $1 = "run" ]
then
    for SEED in $(seq 1 1 $MAXSEED); do
        for data_name in ${data_names[@]}; do
            for TOTAL_SIZE in ${TOTAL_SIZES[@]}; do
                for policy_name in ${policy_names[@]}; do
                    bsub -G SEAS-Lab-Garnett -o /dev/null -J "${data_name}${TOTAL_SIZE}_${policy_name}_${SEED}" "./onerun2 $SEED $data_name $N $TOTAL_SIZE $policy_name"
                done
            done
        done
    done
elif [ $1 = "summary" ]
then
    python utilities/plot_results.py -s $MAXSEED
elif [ $1 = "check" ]
then
    for SEED in $(seq 1 1 $MAXSEED); do
        for data_name in ${data_names[@]}; do
            for TOTAL_SIZE in ${TOTAL_SIZES[@]}; do
                for policy_name in ${policy_names[@]}; do
                    FILE="./results2/${data_name}_N1000_S${TOTAL_SIZE}_${policy_name}_SEED${SEED}.csv"
                    if [ ! -f "$FILE" ]; then
                        echo "$FILE does not exist."
                    fi
                done
            done
        done
    done
fi